django_messages/testapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django_messages import urls as messages_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(messages_urls)),
    # path("__debug__/", include("debug_toolbar.urls")),
]

django_messages/urls.py
from django.urls import path
from . import views as messages_views

app_name = "django_messages"

urlpatterns = [
    path("messages/", messages_views.MessageList.as_view(), name="message_list"),
    path(
        "create_message/", messages_views.MessageCreate.as_view(), name="message_create"
    ),
    path(
        "update_message/<int:pk>/<slug:slug>/",
        messages_views.MessageUpdate.as_view(),
        name="message_update",
    ),
    path(
        "delete_message/<int:pk>/<slug:slug>/",
        messages_views.MessageDelete.as_view(),
        name="message_delete",
    ),
    path(
        "<int:pk>/<slug:slug>/",
        messages_views.MessageView.as_view(),
        name="message_view",
    ),
]

django_messages/models.py
from django import conf, urls, utils
from django.db import models, DEFAULT_DB_ALIAS
from django.contrib import auth
from django.template import defaultfilters


from . import soft_deletion

# django_messages.forms.Message.sanitize_text is a static function that uses bleach
# to sanitize text.  It is called in form.clean_text() but if you create a model,
# and want to sanitize the text, you can do it manually.


class Message(soft_deletion.Model):
    author: models.ForeignKey = models.ForeignKey(
        auth.get_user_model(),
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="%(app_label)s_%(class)s_related",
    )
    text: models.TextField = models.TextField(max_length=500)
    moderation_date: models.DateField = models.DateField(
        null=True, default=None, blank=True
    )
    created_at: models.DateTimeField = models.DateTimeField(auto_now_add=True)
    slug: models.SlugField = models.SlugField(unique=True, db_index=True, max_length=80)

    def get_author_name(self) -> str:
        author = self.author
        if author is None:
            return "anonymous"
        else:
            return author.username

    def __str__(self) -> str:
        return f"'{self.text}' by {self.get_author_name()}"

    def __repr__(self) -> str:
        return f"{self.text}"

    def get_absolute_url(self) -> str:
        return urls.reverse_lazy(
            "django_messages:message_view", args=[self.id, self.slug]
        )  # type: ignore

    def save(
        self,
        force_insert=False,
        force_update=False,
        using=DEFAULT_DB_ALIAS,
        update_fields=None,
    ):
        self.slug = defaultfilters.slugify(
            self.text[:10]
            + "-"
            + str(utils.dateformat.format(utils.timezone.now(), "Y-m-d H:i:s"))
        )
        super().save(force_insert, force_update, using, update_fields)

    class Meta:
        ordering = ["-created_at"]
        app_label = "django_messages"

        try:
            abstract = conf.settings.ABSTRACTMESSAGE
        except AttributeError:
            abstract = False


# class Moderation(models.Model):
# TODO make moderation mixin
#     author: models.ForeignKey = models.ForeignKey(
#         auth.get_user_model(), on_delete=models.SET_NULL, null=True, related_name="moderations")
#     moderation_date: models.DateField = models.DateField(null=True, default=None, blank=True)

#     class Meta:
#         abstract = True

django_messages/forms.py
from crispy_forms import layout, helper

from django import forms, utils, conf

import bleach
import html

from . import models as messages_models

BLANK_TEXT_ERROR = "The message cannot be blank!"
INVALID_TEXT_ERROR = "That is not allowed here."


class Message(forms.ModelForm):
    class Meta:
        model = messages_models.Message
        fields = [
            "text",
            "author",
        ]

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.helper = helper.FormHelper()
        self.helper.layout = layout.Layout(
            layout.Fieldset(
                "",
                layout.Field("text", css_class="mb-3 message-create-form-text"),
                layout.Submit("save", "Save Message", css_class="col-3 mt-3"),
            )
        )
        self.helper.form_id = "id-message-create-form"
        self.helper.form_method = "post"
        self.helper.form_class = "col-auto"
        self.helper.form_action = "django_messages:message_create"

    def clean(self):
        super().clean()
        if self["text"].value() == "" and "text" in self.initial:
            self.cleaned_data["text"] = self.initial["text"]
            self.data = self.data.copy()
            self.data["text"] = self.initial["text"]
        elif self["text"].value() == "":
            self.errors["text"] = BLANK_TEXT_ERROR
        return self.cleaned_data

    def clean_text(self) -> str:
        if self.cleaned_data["text"]:
            self.cleaned_data["text"] = self.sanitize_text(self.cleaned_data["text"])
        if self.cleaned_data["text"] == "":
            if "text" in self.errors:
                try:
                    self.errors["text"].append(INVALID_TEXT_ERROR)
                except AttributeError:
                    self.errors = [self.errors["text"], INVALID_TEXT_ERROR]
            else:
                self.errors["text"] = [INVALID_TEXT_ERROR]
        return self.cleaned_data["text"]

    @staticmethod
    def sanitize_text(text: str) -> utils.safestring.SafeString:
        return utils.safestring.mark_safe(
            bleach.clean(
                html.unescape(text),
                tags=conf.settings.ALLOWED_TAGS,
                attributes=conf.settings.ATTRIBUTES,
                css_sanitizer=conf.settings.CSS_SANITIZER,
                strip=True,
                strip_comments=True,
            )
        )

django_messages/views.py
import logging

from django import urls, utils
from django.contrib.auth import get_user_model
from django.views import generic

from django.views.decorators import cache

from . import models as messages_models
from . import forms as messages_forms

User = get_user_model()

logger = logging.getLogger("django_artisan")


@utils.decorators.method_decorator(cache.never_cache, name="dispatch")
class MessageList(generic.list.ListView):
    model = messages_models.Message
    template_name = "django_messages/message_list.html"
    paginate_by = 6


@utils.decorators.method_decorator(cache.never_cache, name="dispatch")
@utils.decorators.method_decorator(cache.never_cache, name="get")
class MessageView(generic.DetailView):
    model = messages_models.Message
    slug_url_kwarg = "slug"
    slug_field = "slug"
    template_name = "django_messages/message_detail.html"
    form_class = messages_forms.Message
    context_object_name = "message"


class MessageUpdate(generic.UpdateView):
    model = messages_models.Message
    form_class = messages_forms.Message
    template_name_suffix = "_create"
    extra_context = {"instructions": "Update your message..."}


class MessageDelete(generic.edit.DeleteView):
    model = messages_models.Message
    template_name = "django_messages/message_delete.html"
    success_url = urls.reverse_lazy("django_messages:message_list")


class MessageCreate(generic.edit.CreateView):
    model = messages_models.Message
    template_name_suffix = "_create"
    form_class = messages_forms.Message
    extra_context = {"instructions": "Create your message..."}

django_messages/templates/django_messages/base.html
<!DOCTYPE html>
<html lang='en'>
    <head>
        {% load static %}
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}{{ siteName }}{% endblock title %}</title>
        <script
          src="https://code.jquery.com/jquery-3.6.0.slim.min.js"
          integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI="
          crossorigin="anonymous"></script>
        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    </head>
    <body>
        <div class="container-fluid main-container">
          {% block content %}
          {% endblock content %}
        </div> <!-- end .main-container -->
        {% block body_imports %}
        {% endblock body_imports %}
        {% block body_js %}
        {% endblock body_js %}
      </body>
</html>

django_messages/templates/django_messages/message_create.html
{% extends BASE_HTML %}
{% block extra_js %}
{% endblock extra_js %}
{% load static %}
{% block form_media %}
{{ form.media }}
{% endblock form_media %}
{% load crispy_forms_tags %}
{% if user.is_authenticated %}
	{% block content %}
        <div class="container"> 
			<div class="row vh-100">
				<span class="instructions"><h4>{{ instructions }}</h4></span>
				<form method="post" class="col-10 col-sm-10 col-md-8 mx-auto">{% csrf_token %}
				    {% crispy form %}
				</form>
			</div>
		</div>
	{% endblock %}
{% endif %}
{% block body_js %}
{% endblock body_js %}

django_messages/templates/django_messages/message_delete.html
<!DOCTYPE html>
<html>
   <head>
      <title>{{ siteName }} - Delete Message</title>
   </head>
   <body>
      <form method="post">{% csrf_token %}
         <p>Are you sure you want to delete "{{ object }}"?</p>
         <input type="submit" value="Confirm">
      </form>
   </body>
</html>

django_messages/templates/django_messages/message_detail.html
{% extends BASE_HTML %}
{% block title %}{{ siteName }} Message {{ message.id|safe }}{% endblock title %}
{% block form_media %}
{% load static %}
 <script src="{% static 'tinymce/tinymce.min.js' %}" referrerpolicy="origin"></script>
 <script src="{% static 'tinymce/jquery.tinymce.min.js' %}" referrerpolicy="origin"></script>
{% endblock form_media %}
{% block content %}
{% load crispy_forms_tags %}
<div class="container messages-container">
	<div class="row h-75 my-auto">
		<div id='msg_text' class="col-12 col-sm-11 col-md-10 col-lg-8 mx-auto my-auto">
			<div class="row align-items-end">
				<div class="col-auto">
				        <h3>Message {{ message.id|safe }} <span class="text-dark ps-2">by {{ message.author }} on {{ message.created_at }}</span></h3>
			    </div>
			</div>
			<div class="row ms-auto">
			    <div id="textarea" class="col-auto">{{ message.text|safe }}</div>
			    {% if message.author == user %}
				    <div id="msg-edit-div" class="ms-auto">
		    		    <form method="post">
		    		    	{% csrf_token %}
		    		    	<div>
				    		    <input type="hidden" name="type" value="update">
		    		    		<input type="textarea" name="update-msg" class="update-form-text"></input>
				    		    <div class="mt-3">
				                    <button id="editor-cancel-btn" type="button" class="ms-auto col-auto btn btn-secondary me-2">Cancel</button>
				                    <button id="editor-submit-btn" type="submit" class="me-auto col-auto btn btn-primary">
				                    Save Message</button>
				                </div>
			                </div>
		                </form>
		            </div>
                {% endif %}
                </div>
		    </div>
		    <div id="modify-msg-btns" class="row justify-content-end">
	    		{% if message.author == user %}
	    		    <form class="message-delete-form" method="post" action="{% url 'django_messages:message_delete'  message.id message.slug %}">
	    		    {% csrf_token %}
	    		    <button type="submit" class="btn btn-primary">Delete Message</button>
	    		    </form>
		    		<button id="editor-btn" class="me-auto col-auto btn btn-primary">Edit Message</button>
	    		{% endif %}
		    </div>
		</div>
	</div>
</div>
{% endblock %}
{% block body_js %}
<script src="{% static 'django_messages/js/message_detail.js' %}" type="application/javascript" referrerpolicy="origin"></script>
{% endblock body_js %}

django_messages/templates/django_messages/message_list.html
{% extends BASE_HTML %}
{% block title %}{{ siteName }} - Message list{% endblock title %}
{% block content %}
    {% if not page_obj.object_list.exists %}
        <div class="row">
            <div class="col-auto mx-auto mt-5">
                <p><h3>There are currently no messages.  Why not <a href="{% url 'django_messages:message_create' %}">add</a> one...?</h3></p>
            </div>
        </div>
    {% else %}
        <div class="container-fluid main-container-post">
            <div class="row">
                <div class="col-auto mx-auto headline-text">
                    <h2>Messages...</h2>
                </div>
            </div>
            <div class="mb-3 post-list">
                <table>
                    <tbody id="post-table">
                    <tr class="sub-headline-text">
                        <th>Post Leader</th>
                        <th>Date</th>
                    </tr>
                        {% for message in page_obj.object_list %}
                            <tr >
                                <td>
                                    {% if not message.moderation_date %}
                                            <a href="{{ message.get_absolute_url|safe }}" class="tinfo">{{ message.text|striptags|safe|slice:":40" }}...</a>
                                        {% else %}
                                             Message is awaiting moderation
                                        {% endif %}
                                </td>
                                <td>
                                    {{ message.created_at|date:"D d M" }} at {{ message.created_at|date:"g i s a" }}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="row">
                <div class="col-3 mx-auto fixed-bottom mb-3">
                    <div class="row pagination">
                        <span class="d-flex step-links justify-content-around flex-fill">
                            {% if page_obj.has_previous %}
                                <a href="?page=1">&laquo; first</a>
                                <a href="?page={{ page_obj.previous_page_number }}">...previous</a>
                            {% endif %}

                            <span class="current">
                                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                            </span>

                            {% if page_obj.has_next %}
                                <a href="?page={{ page_obj.next_page_number }}">next...</a>
                                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                            {% endif %}
                        </span>
                    </div>
                </div>
            </div>
        </div>
    {% endif %} 
{% endblock %}